import { Router, type IRouter } from "express";
import healthRouter from "./health";
import ageConfirmationRouter from "./age-confirmation";
import siteRouter from "./site";
import progressRouter from "./progress";
import adminRouter from "./admin";
import filmmakerRouter from "./filmmaker";
import pitchReviewCheckoutRouter from "./pitch-review-checkout";
import filmmakerAccountsRouter from "./filmmaker-accounts";
import filmmakerMediaRouter from "./filmmaker-media";
import filmmakerDraftMaterialsRouter from "./filmmaker-draft-materials";
import filmmakerPhoneRouter from "./filmmaker-phone";
import locationsRouter from "./locations";
import projectsRouter from "./projects";
import questionsRouter from "./questions";
import exploreRouter from "./explore";
import investorRouter from "./investor";
import investorReviewRouter from "./investor-review";
import interestAlertsRouter from "./interest-alerts";
import conversationsRouter from "./conversations";
import adminConversationsRouter from "./admin-conversations";
import replitAuthRouter from "./replit-auth";
import referralsRouter from "./referrals";

const router: IRouter = Router();

router.use(replitAuthRouter);
router.use(referralsRouter);
router.use(healthRouter);
router.use(ageConfirmationRouter);
router.use(siteRouter);
router.use(progressRouter);
router.use(adminRouter);
router.use(investorReviewRouter);
router.use(filmmakerRouter);
router.use(pitchReviewCheckoutRouter);
router.use(filmmakerAccountsRouter);
router.use(filmmakerMediaRouter);
router.use(filmmakerDraftMaterialsRouter);
router.use(filmmakerPhoneRouter);
router.use(locationsRouter);
router.use(projectsRouter);
router.use(questionsRouter);
router.use(exploreRouter);
router.use(investorRouter);
router.use(interestAlertsRouter);
router.use(conversationsRouter);
router.use(adminConversationsRouter);

export default router;
